#!/usr/bin/env bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" spalloc <<-EOSQL
    CREATE USER IF NOT EXISTS '${SPRING_DATASOURCE_USERNAME}'@'%' IDENTIFIED BY '${SPRING_DATASOURCE_PASSWORD}';
    GRANT ALL PRIVILEGES ON spalloc.* TO '${SPRING_DATASOURCE_USERNAME}'@'%';
    GRANT ALL PRIVILEGES ON spalloc_history.* TO '${SPRING_DATASOURCE_USERNAME}'@'%';
    GRANT SUPER ON *.* TO '${SPRING_DATASOURCE_USERNAME}'@'%';
    FLUSH PRIVILEGES;
EOSQL
