# Copyright (c) 2021 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

logging:
  level:
    root: INFO
    # "[org.apache.catalina]": DEBUG
    # "[org.springframework.security.web]": TRACE

    "[org.springframework.security.web.csrf.CsrfFilter]": DEBUG
    # Because when that filter says no it is MYSTERIOUS otherwise!

    # Next, two loggers that are unacceptably noisy by default
    "[org.apache.jasper.servlet.TldScanner]": WARN
    "[javax.persistence.spi]": ERROR

spring:
  main:
    banner-mode: off
  application:
    name: spalloc
  mvc:
    servlet:
      path: /system
  task:
    scheduling:
      pool:
        # Default thread pool size. Note that the thread pool is shared by many
        # things inside the service; if this value is too small, performance
        # may be severely impacted or requests may fail.
        size: 16
  mail:
    # Configuring email is fiddly; see docs for how.
    # See https://www.baeldung.com/spring-email
    # See https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/html/boot-features-email.html
    host: smtp.gmail.com
    port: 587
    username: "${EMAIL_USER:}"
    password: "${EMAIL_PASS:}"
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
  security:
    oauth2:
      client:
        registration:
          hbp-ebrains:
            client-id: ${spalloc.auth.openid.id}
            client-secret: ${spalloc.auth.openid.secret}
            scope:
            - openid
            - profile
            - team
            - group
        provider:
          hbp-ebrains:
            authorization-uri: https://iam.ebrains.eu/auth/realms/hbp/protocol/openid-connect/auth
            jwk-set-uri: https://iam.ebrains.eu/auth/realms/hbp
            token-uri: https://iam.ebrains.eu/auth/realms/hbp/protocol/openid-connect/token
            user-info-uri: https://iam.ebrains.eu/auth/realms/hbp/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: https://iam.ebrains.eu/auth/realms/hbp
        opaquetoken:
          client-id: ${spalloc.auth.openid.id}
          client-secret: ${spalloc.auth.openid.secret}

server:
  port: 8080

cxf:
  path: /srv
  servlet.init: 
    service-list-path: info
  jaxrs:
    component-scan: true
    classes-scan-packages:
      uk.ac.manchester.spinnaker.alloc,org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics

# TODO: Don't set auth.add-dummy-user, transceiver.dummy or auth.debug-failures in production
spalloc:
  # Where's the database?
  database-path: spalloc.sqlite3
  # How long should long calls take before returning anyway?
  wait: 30s
  historical-data:
    # Where to we back up old jobs to?
    path: spalloc-history.sqlite3
    # How long before we move old jobs to the historical data
    # Defaults to 14 days (or thereabouts)
    grace-period: P14D
    # Cron-like expression to say when to run the migration task.
    # Defaults to overnight at 02:00 every day
    schedule: "0 0 2 * * *"
  keepalive:
    # How long between runs of the keepalive-expiry algorithm
    expiry-period: PT30S
    # Minimum keepalive period
    min: 30s
    # Maximum keepalive period
    max: 300s
  allocator:
    # How long between runs of the allocator algorithm
    period: PT5S
    # What span of importance will be considered when allocating jobs
    importance-span: 10000
    # Priority is the rate at which importance is accrued
    priority-scale:
      # Priority scaling factor for jobs specified by number of boards
      # Will be multiplied by the number of boards
      size: 1.0
      # Priority scaling factor for jobs specified by rectangular dimensions
      # Will be multiplied by the area of the allocation
      dimensions: 1.5
      # Priority scaling factor for jobs requesting a specific board
      specific-board: 65.0
    report-email:
      # In addition to configuring the email sender, you need to turn on
      # sending here too.
      send: false
      from: spalloc@localhost
      to: SPINNAKER@listserv.manchester.ac.uk
      subject: Spalloc Board Issue
  auth:
    # Support HTTP Basic Authentication (bad for browsers, OK for code)
    basic: true
    # Support HTTP Form Authentication (pretty necessary)
    local-form: true
    # Support OIDC
    oidc: true
    # Force a known local admin user to exist with a known password
    add-dummy-user: true
    # Whether to generate a random password for the above user.
    # If so, the password will be written to the log.
    dummy-random-pass: false
    # Provide extra information to callers on auth failures
    debug-failures: false
    # Number of login failures before lock-out
    max-login-failures: 3
    # Duration of automatic log-out
    account-lock-duration: PT24H
    # How often do we look for users to unlock
    unlock-period: PT60S
    openid:
      # The credentials for HBP/EBRAINS go here
      id: XYZZY_OVERRIDE_THIS
      secret: XYZZY_OVERRIDE_THIS
      # Prefix all OpenID-sourced names with this
      username-prefix: "openid."
  quota:
    # Default user quota in board-seconds
    default: 100
    # When do we consolidate job quotas into the main quota table
    consolidation-schedule: "0 0 * * * *"
  transceiver:
    # How long between when we send requests to the BMP control tasks
    period: PT10S
    # The basic wait time used by the BMP control tasks
    probe-interval: 15s
    # Number of attempts that will be made to switch on a board
    power-attempts: 2
    # Number of attempts that will be made to bring up an FPGA
    fpga-attempts: 3
    # Whether to use dummy BMPs; GREAT for testing!
    dummy: false
  sqlite:
    # How long to wait to get a DB lock
    timeout: 1s
    # Whether to send details of SQL-related exceptions to users
    debug-failures: false
    # Amount of effort to spend on DB optimization on application close
    analysis-limit: 400
  compat:
    # Settings relating to the v1 spalloc compatibility interface

    # Whether to turn the service interface on
    enable: false
    # The number of threads to use for the API (including notification handlers)
    # Use 0 for no hard limit.
    thread-pool-size: 0
    # What port to run the service on
    port: 22244
    # What user to run as; recommended that this user exists but is disabled
    service-user: ""
