# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# Copyright (c) 2020-2022 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Build and Test
on: 
  push:
    # On any push to any branch
  schedule:
    # Build daily on the default branch at 04:40
    - cron: "40 4 * * *"
env:
  SETTINGS_FILE: .github/settings.xml

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Minimum Java version!
        java: [11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.4.1
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'

    - name: Compile
      run: mvn clean install --settings $SETTINGS_FILE -B -DskipTests=true -Dmaven.javadoc.skip=true -P "!jsp-precompile"

  test:
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14, 17]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3.4.1
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'

    - name: Build with Java ${{ matrix.java }}
      run: mvn install --settings $SETTINGS_FILE -DskipTests=true -Dmaven.javadoc.skip=true
    - name: "Check: Test"
      run: mvn verify --settings $SETTINGS_FILE -Dmaven.javadoc.skip=true jacoco:report
    - name: "Report: Coverage via coveralls.io"
      run: |
        export CI_BRANCH=${BRANCH_NAME_OR_REF#refs/heads/}
        export CI_PULL_REQUEST=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        mvn coveralls:report --settings $SETTINGS_FILE --no-transfer-progress -DrepoToken=$COVERALLS_SECRET
      env:
        CI_NAME: github
        BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
        CI_BUILD_NUMBER: ${{ github.run_id }}
        CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
        COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Upload Build (JDK 11 only)
      if: matrix.java == 11
      uses: actions/upload-artifact@v3
      with:
        name: spinnaker-exe.jar
        path: SpiNNaker-front-end/target/spinnaker-exe.jar
        retention-days: 5

  validate:
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.4.1
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'

    - name: "Check: Code Style"
      run: mvn directory:highest-basedir@find-root checkstyle:check --settings $SETTINGS_FILE
    - name: "Check: Documentation"
      run: mvn javadoc:aggregate --settings $SETTINGS_FILE -P "!jsp-precompile"

  minor-style:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3.4.1
      with:
        distribution: 'zulu'
        java-version: 11
        cache: 'maven'

    - name: "Check: No FIXMEs left"
      run: mvn exec:exec@check-for-fixme --settings $SETTINGS_FILE -P CheckForFIXME
    - name: "Check: copyright declarations"
      run: mvn apache-rat:check --settings $SETTINGS_FILE -V || (find . -type f -name 'rat*.txt' -print | xargs grep -l unapproved | xargs cat; exit 1)
